### ISSUE TITLE
How to run waves-typo?

### ISSUE THREAD

**Issue by successhalf** [deemru/waves-typo#1]
How to run your program

**Comment by deemru** [comment]
Run the program in cmd, usage in the description:
```
C:\temp>waves-typo.exe
waves-typo (Sep 20 2018)
Usage: waves-typo.exe "address" "seed"
```

**Comment by successhalf** [comment]
> waves-typo.exe "address" "seed"
waves-typo>waves-typo.exe "address" "seed"
waves-typo (Sep 20 2018)
Bad MAINNET address: address

**Comment by deemru** [comment]
It is obvious: "address" should be Waves Platform address and "seed" must be a part of known seed to recover.

To get to the basics, please refer https://docs.wavesplatform.com

**Comment by successhalf** [comment]
> It is obvious: "address" should be Waves Platform address and "seed" must be a part of known seed to recover.
> 
> To get to the basics, please refer https://docs.wavesplatform.com

I tried with some structures
waves-typo>waves-typo.exe "16h2swdYMyd9UHhHztf3R
wvRp41MdNpcTE" "keen patrol speak stadium wasp"
waves-typo (Sep 20 2018)
Bad MAINNET address: 16h2swdYMyd9UHhHztf3RwvRp41MdNpcTE
