### ISSUE TITLE
Need upgrade/modify

### ISSUE THREAD

**Issue by CryptoRecoveryWorldwideCZ** [deemru/waves-typo#2]
Hi. Is possible to edit it for only step 1? My friend lost one word from seed to Wawes. His friend wrote code for finding word from wordlist on any position. BUT: when i try it /his code/ work only for one word position in SEED, and if tryed word isnt correct, not try other word in wordlist, but Your program try to find last 2 words in the seed as step 2. Is possible to finding only one word from wordlist, but on different positions? Or simply delete step 2 from program? Very thanks for reply. Jiri

**Comment by deemru** [comment]
input 14 words, look for missing word at any position?

it is https://github.com/deemru/waves-typo/releases/tag/1.0.4 (step 1)

**Comment by CryptoRecoveryWorldwideCZ** [comment]
yes, i dont know, where is correct possition for 1 word. I dont need other steps, which your program do, it is waste of time. Is possible to run only step 1? Or I have programmner, but you havent got in repository, as my friend say: project.

**Comment by deemru** [comment]
Step 1 done in less of a second, just Ctrl+C if you do not need other steps.

Or you can edit the code and compile yourself for your needs.

**Comment by CryptoRecoveryWorldwideCZ** [comment]
My friends other friend do this:

@echo on
for /f "delims=" %%a in (seed.txt) DO (
  echo %%a
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "%%a sponsor scout phone pistol analyst top rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor %%a scout phone pistol analyst top rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout %%a phone pistol analyst top rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone %%a pistol analyst top rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol %%a analyst top rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run witness task circle uniform target faint %%a"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst %%a top rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top %%a rug run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug %%a run witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run %%a witness task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run witness %%a task circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run witness task %%a circle uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run witness task circle %%a uniform target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run witness task circle uniform %%a target faint"
  waves-typo.exe "3PHSXYFNt9xbGWqauHYvNHxZXRKni6mno78" "sponsor scout phone pistol analyst top rug run witness task circle uniform target %%a faint"
  )

This do step one, on each position, but before trying next position, must your program ends step 2 on latest release. Then this script try next position. But step 2 takes very long time on Core i5 /about 3-5minutes each/.

**Comment by CryptoRecoveryWorldwideCZ** [comment]
Yes, this takes for one word 30720times :)) about 56 Hours, i try first position by hands, 136 times for 15 minutes. This above is wallet for tests.

**Comment by CryptoRecoveryWorldwideCZ** [comment]
where I do edit code? I am "programmer" amateur, this is above my skills.

**Comment by CryptoRecoveryWorldwideCZ** [comment]
If your code have only step 1, this script automatically in seconds try next position. When not find correct possition, then try next word. I hope, you can help me.

**Comment by deemru** [comment]
Ok, let me try

**Comment by CryptoRecoveryWorldwideCZ** [comment]
Thank you so much

**Comment by deemru** [comment]
https://github.com/deemru/waves-typo/releases/tag/1.0.7

**Comment by CryptoRecoveryWorldwideCZ** [comment]
I will try it now, thank you!

**Comment by CryptoRecoveryWorldwideCZ** [comment]
WORKS!!!!!!!!!!!!!!!! :))) I love you man!! :))
